``` plantuml
@startuml
class Cliente {
  - String rg
  - String cpf
  - String nome
  - String endereco
  - String profissao
  - Double[] rendimentos
}

class Automovel {
  - String matricula
  - int ano
  - String marca
  - String modelo
  - String placa
}

class PedidoAluguel {
  - Long id
  - String status
  - Boolean temCredito
}

class Agente {
  - String nome
  - String tipo
}

Cliente "1" -- "0..*" PedidoAluguel
Agente "1" -- "0..*" PedidoAluguel : avalia >
PedidoAluguel "0..*" -- "1" Automovel
@enduml
```