micronaut.application.name=demo

datasources.default.url=jdbc:postgresql://localhost:5432/aluguel_carros
datasources.default.driverClassName=org.postgresql.Driver
datasources.default.username=postgres
datasources.default.password=2209

jpa.default.properties.hibernate.hbm2ddl.auto=update
jpa.default.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

micronaut.router.static-resources.css.enabled=true
micronaut.router.static-resources.css.mapping=/css/**
micronaut.router.static-resources.css.paths=classpath:static/css

micronaut.router.static-resources.carros.enabled=true
micronaut.router.static-resources.carros.mapping=/carros/**
micronaut.router.static-resources.carros.paths=classpath:static/carros