# Nome da aplicação
micronaut.application.name=demo

# Banco H2 persistente em arquivo
datasources.default.url=jdbc:h2:file:./data/alugueldb
datasources.default.driverClassName=org.h2.Driver
datasources.default.username=sa
datasources.default.password=

# JPA / Hibernate
jpa.default.properties.hibernate.hbm2ddl.auto=update